// Generated by lsc from ring-cursor.ts

function JSRem(a: int, b: int): int
  requires b != 0
{
  var r := (if a < 0 then -a else a) % (if b < 0 then -b else b);
  if a < 0 then -r else r
}

datatype RingCursor = RingCursor(front: int, back: int, full: bool)

function lengthValue(capacity: int, front: int, back: int, full: bool): int
  requires (capacity > 0)
  requires (front >= 0)
  requires (front < capacity)
  requires (back >= 0)
  requires (back < capacity)
  requires (!(full) || (front == back))
{
  if full then
    capacity
  else
    if (front <= back) then
      (back - front)
    else
      ((capacity - front) + back)
}

lemma lengthValue_ensures(capacity: int, front: int, back: int, full: bool)
  requires (capacity > 0)
  requires (front >= 0)
  requires (front < capacity)
  requires (back >= 0)
  requires (back < capacity)
  requires (!(full) || (front == back))
  ensures (lengthValue(capacity, front, back, full) >= 0)
  ensures (lengthValue(capacity, front, back, full) <= capacity)
  ensures ((lengthValue(capacity, front, back, full) == capacity) == full)
{
}

function advanceIndex(capacity: int, index: int, count: int): int
  requires (capacity > 0)
  requires (index >= 0)
  requires (index < capacity)
  requires (count >= 0)
  requires (count <= capacity)
{
  var remaining := (capacity - index);
  if (count >= remaining) then
    (count - remaining)
  else
    (index + count)
}

lemma advanceIndex_ensures(capacity: int, index: int, count: int)
  requires (capacity > 0)
  requires (index >= 0)
  requires (index < capacity)
  requires (count >= 0)
  requires (count <= capacity)
  ensures (advanceIndex(capacity, index, count) >= 0)
  ensures (advanceIndex(capacity, index, count) < capacity)
  ensures ((count == 0) ==> (advanceIndex(capacity, index, count) == index))
  ensures (advanceIndex(capacity, index, count) == JSRem((index + count), capacity))
{
}

function fullAfterWrite(front: int, back: int, full: bool, count: int): bool
  requires (count >= 0)
{
  if (count > 0) then
    (front == back)
  else
    full
}

lemma fullAfterWrite_ensures(front: int, back: int, full: bool, count: int)
  requires (count >= 0)
  ensures ((count == 0) ==> (fullAfterWrite(front, back, full, count) == full))
  ensures ((count > 0) ==> (fullAfterWrite(front, back, full, count) == (front == back)))
{
}

function fullAfterRead(full: bool, count: int): bool
  requires (count >= 0)
{
  if (count > 0) then
    false
  else
    full
}

lemma fullAfterRead_ensures(full: bool, count: int)
  requires (count >= 0)
  ensures ((count == 0) ==> (fullAfterRead(full, count) == full))
  ensures ((count > 0) ==> !(fullAfterRead(full, count)))
{
}

function cursorLength(capacity: int, cursor: RingCursor): int
  requires (capacity > 0)
  requires (cursor.front >= 0)
  requires (cursor.front < capacity)
  requires (cursor.back >= 0)
  requires (cursor.back < capacity)
  requires (!(cursor.full) || (cursor.front == cursor.back))
{
  lengthValue(capacity, cursor.front, cursor.back, cursor.full)
}

lemma cursorLength_ensures(capacity: int, cursor: RingCursor)
  requires (capacity > 0)
  requires (cursor.front >= 0)
  requires (cursor.front < capacity)
  requires (cursor.back >= 0)
  requires (cursor.back < capacity)
  requires (!(cursor.full) || (cursor.front == cursor.back))
  ensures (cursorLength(capacity, cursor) >= 0)
  ensures (cursorLength(capacity, cursor) <= capacity)
  ensures ((cursorLength(capacity, cursor) == capacity) == cursor.full)
{
}

function commitWrite(capacity: int, cursor: RingCursor, count: int): RingCursor
  requires (capacity > 0)
  requires (cursor.front >= 0)
  requires (cursor.front < capacity)
  requires (cursor.back >= 0)
  requires (cursor.back < capacity)
  requires (!(cursor.full) || (cursor.front == cursor.back))
  requires (count >= 0)
  requires (count <= (capacity - cursorLength(capacity, cursor)))
{
  var back := advanceIndex(capacity, cursor.back, count);
  RingCursor(cursor.front, back, fullAfterWrite(cursor.front, back, cursor.full, count))
}

lemma commitWrite_ensures(capacity: int, cursor: RingCursor, count: int)
  requires (capacity > 0)
  requires (cursor.front >= 0)
  requires (cursor.front < capacity)
  requires (cursor.back >= 0)
  requires (cursor.back < capacity)
  requires (!(cursor.full) || (cursor.front == cursor.back))
  requires (count >= 0)
  requires (count <= (capacity - cursorLength(capacity, cursor)))
  ensures (commitWrite(capacity, cursor, count).front >= 0)
  ensures (commitWrite(capacity, cursor, count).front < capacity)
  ensures (commitWrite(capacity, cursor, count).back >= 0)
  ensures (commitWrite(capacity, cursor, count).back < capacity)
  ensures (!(commitWrite(capacity, cursor, count).full) || (commitWrite(capacity, cursor, count).front == commitWrite(capacity, cursor, count).back))
  ensures (cursorLength(capacity, commitWrite(capacity, cursor, count)) == (cursorLength(capacity, cursor) + count))
  ensures (commitWrite(capacity, cursor, count).front == cursor.front)
  ensures ((count == 0) ==> ((commitWrite(capacity, cursor, count).back == cursor.back) && (commitWrite(capacity, cursor, count).full == cursor.full)))
{
}

function commitRead(capacity: int, cursor: RingCursor, count: int): RingCursor
  requires (capacity > 0)
  requires (cursor.front >= 0)
  requires (cursor.front < capacity)
  requires (cursor.back >= 0)
  requires (cursor.back < capacity)
  requires (!(cursor.full) || (cursor.front == cursor.back))
  requires (count >= 0)
  requires (count <= cursorLength(capacity, cursor))
{
  RingCursor(advanceIndex(capacity, cursor.front, count), cursor.back, fullAfterRead(cursor.full, count))
}

lemma commitRead_ensures(capacity: int, cursor: RingCursor, count: int)
  requires (capacity > 0)
  requires (cursor.front >= 0)
  requires (cursor.front < capacity)
  requires (cursor.back >= 0)
  requires (cursor.back < capacity)
  requires (!(cursor.full) || (cursor.front == cursor.back))
  requires (count >= 0)
  requires (count <= cursorLength(capacity, cursor))
  ensures (commitRead(capacity, cursor, count).front >= 0)
  ensures (commitRead(capacity, cursor, count).front < capacity)
  ensures (commitRead(capacity, cursor, count).back >= 0)
  ensures (commitRead(capacity, cursor, count).back < capacity)
  ensures (!(commitRead(capacity, cursor, count).full) || (commitRead(capacity, cursor, count).front == commitRead(capacity, cursor, count).back))
  ensures (cursorLength(capacity, commitRead(capacity, cursor, count)) == (cursorLength(capacity, cursor) - count))
  ensures (commitRead(capacity, cursor, count).back == cursor.back)
  ensures ((count == 0) ==> ((commitRead(capacity, cursor, count).front == cursor.front) && (commitRead(capacity, cursor, count).full == cursor.full)))
{
}
